version: '3.8'

services:
  payment-gateway-api:
    build:
      context: ./src
      dockerfile: Api/Dockerfile
    ports:
      - "5000:80"
    environment:
      AcquiringBank__BaseUrl: "http://bank-simulator"
    networks:
      - payment-network

  bank-simulator:
    build:
      context: ./src
      dockerfile: BankSimulator/Dockerfile
    ports:
      - "5500:80"
    networks:
      - payment-network

networks:
  payment-network:
